import { CustomTerraceType } from "../../../models/terrace-model/zod/customTerrace-schema.js";
import { defaultOpeningHours } from "../../../utils/terrace-utils/defaultOpeningHours.js";

export const mockCustomTerrace: CustomTerraceType = {
    id: "terrace-001",
    business_name: "Terrassa Guapa",
    cadastro_ref: "REF-XYZ-123",
    address: "C. Santa Eulalia, 46",
    activity_code: 1010,
    group_activity_code: 1000,
    district_name: "Eixample",
    district_code: 2,
    neighbourhood_name: "La Dreta de l'Eixample",
    neighbourhood_code: 21,
    zip_code: "08008",
    tables: 8,
    seats: 32,
    latitude: "41.390205",
    longitude: "2.154007",
    average_price: 24.5,
    average_rating: 4.3,
    has_wifi: true,
    pet_friendly: true,
    can_smoke: false,
    has_disabled_access: true,
    has_kitchen: false,
    reservation_fee: 2.5,
    is_claimed: true,
    instagram_account: "@terrassaguapa",
    website: "https://terrassaguapa.cat",
    profile_pic: "https://linktoterrace1.com",
    id: "biz-12345",
    business_name: "Sunset Café",
    cadastro_ref: "REF-67890",
    street_type: "Avenue",
    street_address: "Sunset Boulevard",
    door_address: 42,
    activity_code: 5630,
    group_activity_code: 5630,
    postal_code: 8902,
    district_name: "Downtown",
    district_code: 1,
    neighbourhood_name: "Arts District",
    neighbourhood_code: 12,
    opening_hours: defaultOpeningHours,
    tables: 10,
    seats: 40,
    latitude: String(41.3851),
    longitude: String(2.1734),
    average_price: undefined,
    average_rating: undefined,
    has_wifi: undefined,
    pet_friendly: undefined,
    can_smoke: undefined,
    has_kitchen: undefined,
    has_promos: false,
    reservation_fee: 0,
    is_premium: false,
    is_verified: false,
    instagram_account: ''
}

export function mockCreateCustomTerrace() {
    return mockCustomTerrace;
}