import { BusinessApiType } from "../../../models/terrace-model/zod/business-schema.js";

// export const businesses: Partial<BusinessApiType>[] = [
//         {
//             Nom_CComercial: "",
//             Seccio_Censal: "23",
//             SN_Eix: "No",
//             Nom_Galeria: "",
//             Codi_Via: "288408",
//             Nom_Eix: "",
//             Codi_Districte: "3",
//             SN_Mixtura: "No",
//             Lletra_Inicial: "",
//             Codi_Activitat_2022: "1300000",
//             Direccio_Unica: "288408, 95-95, LOC 10",
//             ID_Global: "7b00aaf3-8e02-490e-a6ca-16f306bb11d7",
//             Nom_Activitat: "Reparacions (Electrodomèstics i automòbils)",
//             Nom_Mercat: "",
//             Lletra_Final: "",
//             Codi_Principal_Activitat: "1",
//             Num_Policia_Inicial: "95",
//             ID_Bcn_2016: "44961",
//             Nom_Grup_Activitat: "Reparacions (Electrodomèstics i automòbils)",
//             Referencia_Cadastral: "0304318DF3800C",
//             SN_Coworking: "No",
//             Solar: "567648",
//             SN_Mercat: "No",
//             Nom_Via: "ROSER",
//             Longitud: "2.165500224",
//             Codi_Sector_Activitat: "2",
//             X_UTM_ETRS89: "430212.417",
//             Y_UTM_ETRS89: "4580323.935",
//             SN_CComercial: "No",
//             SN_Carrer: "Si",
//             Porta: "10",
//             Codi_Illa: "20440",
//             Planta: "LOC",
//             SN_Servei_Degustacio: "No",
//             Num_Policia_Final: "95",
//             Nom_Principal_Activitat: "Actiu",
//             Nom_Local: "TALLERS ROSER REPARACIO GENERAL DE AUTOMOVILES",
//             Codi_Barri: "11",
//             SN_Obert24h: "No",
//             Codi_Activitat_2016: "13000",
//             Latitud: "41.371406328",
//             Codi_Grup_Activitat: "13",
//             SN_Galeria: "No",
//             Nom_Districte: "Sants-Montjuïc",
//             Nom_Sector_Activitat: "Serveis",
//             Codi_Parcela: "18",
//             Nom_Barri: "el Poble Sec",
//             SN_Oci_Nocturn: "No",
//             _id: 1,
//             Data_Revisio: "2023-05-29T00:00:00"
//         },
//         {
//             Nom_CComercial: "",
//             Seccio_Censal: "86",
//             SN_Eix: "No",
//             Nom_Galeria: "",
//             Codi_Via: "240208",
//             Nom_Eix: "",
//             Codi_Districte: "5",
//             SN_Mixtura: "No",
//             Lletra_Inicial: "",
//             Codi_Activitat_2022: "1700700",
//             Direccio_Unica: "240208, 103-103, LOC 10",
//             ID_Global: "3a677dd7-d46a-4061-9f0f-9e56d4d2e7de",
//             Nom_Activitat: "Arts gràfiques",
//             Nom_Mercat: "",
//             Lletra_Final: "",
//             Codi_Principal_Activitat: "1",
//             Num_Policia_Inicial: "103",
//             ID_Bcn_2016: "25290",
//             Nom_Grup_Activitat: "Altres",
//             Referencia_Cadastral: "8541602DF2884B",
//             SN_Coworking: "No",
//             Solar: "137714",
//             SN_Mercat: "No",
//             Nom_Via: "PÀDUA",
//             Longitud: "2.143923193",
//             Codi_Sector_Activitat: "3",
//             X_UTM_ETRS89: "428443.827",
//             Y_UTM_ETRS89: "4583972.556",
//             SN_CComercial: "No",
//             SN_Carrer: "Si",
//             Porta: "10",
//             Codi_Illa: "31420",
//             Planta: "LOC",
//             SN_Servei_Degustacio: "No",
//             Num_Policia_Final: "103",
//             Nom_Principal_Activitat: "Actiu",
//             Nom_Local: "SPEED COPY",
//             Codi_Barri: "27",
//             SN_Obert24h: "No",
//             Codi_Activitat_2016: "17007",
//             Latitud: "41.404112785",
//             Codi_Grup_Activitat: "17",
//             SN_Galeria: "No",
//             Nom_Districte: "Sarrià-Sant Gervasi",
//             Nom_Sector_Activitat: "Altres",
//             Codi_Parcela: "2",
//             Nom_Barri: "el Putxet i el Farró",
//             SN_Oci_Nocturn: "No",
//             _id: 2,
//             Data_Revisio: "2023-07-06T00:00:00"
//         },
//         {
//             Nom_CComercial: "",
//             Seccio_Censal: "43",
//             SN_Eix: "Si",
//             Nom_Galeria: "",
//             Codi_Via: "206403",
//             Nom_Eix: "Gran de Gràcia",
//             Codi_Districte: "6",
//             SN_Mixtura: "No",
//             Lletra_Inicial: "",
//             Codi_Activitat_2022: "3002000",
//             Direccio_Unica: "206403, 41-43, LOC 10",
//             ID_Global: "1e72fa31-3113-4a89-acb5-666e518b2669",
//             Nom_Activitat: "Material equipament llar",
//             Nom_Mercat: "",
//             Lletra_Final: "",
//             Codi_Principal_Activitat: "1",
//             Num_Policia_Inicial: "41",
//             ID_Bcn_2016: "27506",
//             Nom_Grup_Activitat: "Parament de la llar",
//             Referencia_Cadastral: "9436713DF2893E",
//             SN_Coworking: "No",
//             Solar: "144501",
//             SN_Mercat: "No",
//             Nom_Via: "GRAN DE GRÀCIA",
//             Longitud: "2.156260014",
//             Codi_Sector_Activitat: "1",
//             X_UTM_ETRS89: "429469.551",
//             Y_UTM_ETRS89: "4583400.578",
//             SN_CComercial: "No",
//             SN_Carrer: "Si",
//             Porta: "10",
//             Codi_Illa: "80380",
//             Planta: "LOC",
//             SN_Servei_Degustacio: "No",
//             Num_Policia_Final: "43",
//             Nom_Principal_Activitat: "Actiu",
//             Nom_Local: "DORMITY.COM",
//             Codi_Barri: "31",
//             SN_Obert24h: "No",
//             Codi_Activitat_2016: "3002",
//             Latitud: "41.399051836",
//             Codi_Grup_Activitat: "3",
//             SN_Galeria: "No",
//             Nom_Districte: "Gràcia",
//             Nom_Sector_Activitat: "Comerç al detall",
//             Codi_Parcela: "13",
//             Nom_Barri: "la Vila de Gràcia",
//             SN_Oci_Nocturn: "No",
//             _id: 3,
//             Data_Revisio: "2023-03-02T00:00:00"
//         },
//         {
//             Nom_CComercial: "",
//             Seccio_Censal: "21",
//             SN_Eix: "Si",
//             Nom_Galeria: "",
//             Codi_Via: "34308",
//             Nom_Eix: "La Rambla",
//             Codi_Districte: "1",
//             SN_Mixtura: "No",
//             Lletra_Inicial: "",
//             Codi_Activitat_2022: "2002000",
//             Direccio_Unica: "034308, 121-121, LOC 20",
//             ID_Global: "d6bc5661-c934-43cd-a87c-d4f3678bedb0",
//             Nom_Activitat: "Farmàcies PARAFARMÀCIA",
//             Nom_Mercat: "",
//             Lletra_Final: "",
//             Codi_Principal_Activitat: "1",
//             Num_Policia_Inicial: "121",
//             ID_Bcn_2016: "9285",
//             Nom_Grup_Activitat: "Quotidià no alimentari",
//             Referencia_Cadastral: "0619508DF3801H",
//             SN_Coworking: "No",
//             Solar: "63229",
//             SN_Mercat: "No",
//             Nom_Via: "RAMBLA",
//             Longitud: "2.170435488",
//             Codi_Sector_Activitat: "1",
//             X_UTM_ETRS89: "430639.065",
//             Y_UTM_ETRS89: "4581774.118",
//             SN_CComercial: "No",
//             SN_Carrer: "Si",
//             Porta: "20",
//             Codi_Illa: "50550",
//             Planta: "LOC",
//             SN_Servei_Degustacio: "No",
//             Num_Policia_Final: "121",
//             Nom_Principal_Activitat: "Actiu",
//             Nom_Local: "FARMACIA NADAL",
//             Codi_Barri: "1",
//             SN_Obert24h: "No",
//             Codi_Activitat_2016: "2002",
//             Latitud: "41.38450457",
//             Codi_Grup_Activitat: "2",
//             SN_Galeria: "No",
//             Nom_Districte: "Ciutat Vella",
//             Nom_Sector_Activitat: "Comerç al detall",
//             Codi_Parcela: "8",
//             Nom_Barri: "el Raval",
//             SN_Oci_Nocturn: "No",
//             _id: 4,
//             Data_Revisio: "2023-02-17T00:00:00"
//         }
// ]